name: 部署文档

on:
  push:
    branches:
      - wiki

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true # false 使用 personal token，true 则使用 GitHub token
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          # submodules: true



      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: 安装依赖
        run: |
          corepack enable
          npm ci

      - name: 构建文档
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          npm run docs:build
          > src/.vuepress/dist/.nojekyll

      - name: 部署文档
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: src/.vuepress/dist
      # - name: 部署到公开仓库  # https://zhuanlan.zhihu.com/p/541944539
      #   working-directory: src/.vuepress/dist
      #   run: |
      #      git init
      #      git checkout -b gh-pages
      #      git add -A
      #      git remote add origin https://github.com/Yanguan619/Yanguan619.git
      #      git push origin gh-pages -f -q