# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Blog CI

on:
  push:
    branches: [ "pages" ]
    paths: # 监测所有 source 目录下的文件变动，所有 yml,json 后缀文件的变动。
      - '*.json'
      - '**.yml'
      - '**/source/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    # 安装源代码所需插件
    - name: Init Node.js 
      run: |
          npm install
          echo "init node successful"
    # 安装 Hexo
    - name: Install Hexo-cli 
      run: |
          npm install -g hexo-cli --save
          echo "install hexo successful"
    # 编译创建静态博客文件
    - name: Build Blog
      run: |
          hexo clean
          hexo g
          echo "build blog successful"
    # 设置 git 信息并推送静态博客文件
    - name: Deploy Blog 
      run: |
          git config --global user.name "Yanguan619"
          git config --global user.email "1131595527@qq.com"
          hexo deploy
    # 完成
    - run: echo "Deploy Successful!"
